const actionTypes = {
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  REMOVE_INGREDIENT: 'REMOVE_INGREDIENT',
  FETCH_INGREDIENTS: 'FETCH_INGREDIENTS',
  FETCH_INGREDIENTS_FAILED: 'FETCH_INGREDIENTS_FAILED'
}

export default actionTypes;